'use client';
import { useEffect,useRef,useState } from 'react';
import AccountCenter,{PasswordRecovery} from './account-center';
import PublicSignupSettings from './signup-settings';
import MemberEditor from './member-editor';
import { Camera,Upload,Images,Folder,Users,ShieldCheck,LockKeyhole,LogOut,Plus,ArrowDownToLine,Share2,Film,Check,Trash2,KeyRound,Cloud,ChevronRight,RotateCcw,ImageIcon } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Sidebar, SidebarProvider } from '@/components/ui/sidebar';
import { Input } from '@/components/ui/input';
import { Dialog,DialogContent,DialogTitle,DialogDescription } from '@/components/ui/dialog';
import { Tabs,TabsList,TabsTrigger } from '@/components/ui/tabs';
import { Checkbox } from '@/components/ui/checkbox';
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from '@/components/ui/select';
import { AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction } from '@/components/ui/alert-dialog';
const API='/api/vault/';
const roleName=(role:string)=>role==='owner'?'Primary admin':role==='admin'?'Admin':'Member';
let expectedUserId:string|null=null;
async function api(path:string,data?:any,method?:string){
 const headers:Record<string,string>={};if(data)headers['Content-Type']='application/json';
 const publicPath=['login','setup','status','forgot-password','signup'].includes(path);if(expectedUserId&&!publicPath)headers['x-vault-user']=expectedUserId;
 const r=await fetch(API+path,{method:method||(data?'POST':'GET'),credentials:'same-origin',cache:'no-store',headers,body:data?JSON.stringify(data):undefined});
 const b:any=await r.json();if(!r.ok){const sessionEnded=!publicPath&&(r.status===401||b.code==='SESSION_CHANGED');if(sessionEnded)window.dispatchEvent(new CustomEvent('vault-session-ended'));throw Object.assign(new Error(b.error||'Please try again.'),{sessionEnded})}return b;
}
const bytes=(n:number)=>n>=1024**3?(n/1024**3).toFixed(1)+' GB':n>=1024**2?(n/1024**2).toFixed(1)+' MB':Math.ceil(n/1024)+' KB';
const hash=async(b:ArrayBuffer)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',b)),x=>x.toString(16).padStart(2,'0')).join('');
type Job={file:File,id?:string,part:number,verify:number,completed:boolean,status:string,progress:number,error?:string,done?:boolean};
export default function Vault(){
 const [user,setUser]=useState<any>(null),[loading,setLoading]=useState(true),[setup,setSetup]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[view,setView]=useState('mine'),[media,setMedia]=useState<any[]>([]),[albums,setAlbums]=useState<any[]>([]),[members,setMembers]=useState<any[]>([]),[album,setAlbum]=useState('all'),[familyMember,setFamilyMember]=useState('all'),[stats,setStats]=useState({count:0,bytes:0}),[more,setMore]=useState(false),[fetching,setFetching]=useState(false),[modal,setModal]=useState(''),[selected,setSelected]=useState<any>(null),[recipients,setRecipients]=useState<string[]>([]),[busy,setBusy]=useState(false),[jobs,setJobs]=useState<Job[]>([]),[running,setRunning]=useState(false),[target,setTarget]=useState<any>(null),[confirm,setConfirm]=useState<any>(null);
 const [recovery,setRecovery]=useState(false),[signupEnabled,setSignupEnabled]=useState(false),[signup,setSignup]=useState(false);
 const queue=useRef<Job[]>([]),fileInput=useRef<HTMLInputElement>(null),requestVersion=useRef(0),sessionGeneration=useRef(0);
 async function boot(){setLoading(true);try{const s=await api('status');setSetup(s.needsSetup);setSignupEnabled(s.signupEnabled);setSignup(s.signupEnabled&&new URLSearchParams(window.location.search).get('signup')==='1');if(!s.needsSetup){try{const m=await api('me');setUser(m.user)}catch{setUser(null)}}}catch(e:any){if(!e.sessionEnded)setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{if(new URLSearchParams(window.location.search).get('reset-password')==='1'){setRecovery(true);setLoading(false)}else boot()},[]);
 useEffect(()=>{expectedUserId=user?.id||null},[user?.id]);
 useEffect(()=>{if(user||setup||recovery)return;const refresh=()=>api('status').then(s=>{setSignupEnabled(s.signupEnabled);if(!s.signupEnabled)setSignup(false)}).catch(()=>{});window.addEventListener('focus',refresh);const timer=setInterval(refresh,15000);return()=>{window.removeEventListener('focus',refresh);clearInterval(timer)}},[user,setup,recovery]);
 useEffect(()=>{const ended=(event:Event)=>{requestVersion.current++;sessionGeneration.current++;queue.current=[];setJobs([]);expectedUserId=null;setUser(null);setMedia([]);setMembers([]);setAlbums([]);setModal('');setSelected(null);setTarget(null);setConfirm(null);setNotice('');setView('mine');setAlbum('all');setFamilyMember('all');setError('')};window.addEventListener('vault-session-ended',ended);return()=>window.removeEventListener('vault-session-ended',ended)},[]);
 async function load(append=false){if(!user||user.mustChange||view==='account')return;const version=++requestVersion.current;setFetching(true);try{const b=await api('media?view='+view+'&album='+(album==='all'?'':encodeURIComponent(album))+'&member='+(view==='family'&&familyMember!=='all'?encodeURIComponent(familyMember):'')+'&offset='+(append?media.length:0));if(version!==requestVersion.current)return;setMedia(old=>append?[...old,...b.media]:b.media);setStats(b.stats);setMore(b.media.length===100);const [a,m]=await Promise.all([api('albums'),api('members')]);if(version!==requestVersion.current)return;setAlbums(a.albums);setMembers(m.members)}catch(e:any){if(!e.sessionEnded)setError(e.message)}finally{if(version===requestVersion.current)setFetching(false)}}
 useEffect(()=>{setMedia([]);load()},[user,view,album,familyMember]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(running){e.preventDefault();e.returnValue='Uploads are still in progress.'}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[running]);
 useEffect(()=>{const c=(document as any).modelContext;if(!c?.registerTool)return;const a=new AbortController();try{Promise.resolve(c.registerTool({name:'start_media_upload',description:'Open the photo and video upload panel. This does not select or upload files.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:any)=>{if(!input||Object.keys(input).length)throw new Error('No arguments expected');if(!user||user.mustChange)throw new Error('Sign in and change any temporary password first');setModal('upload');return {panel:'upload',filesUploaded:false}}},{signal:a.signal})).catch(()=>{})}catch{}return()=>a.abort()},[user]);
 async function action(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn()}catch(e:any){if(!e.sessionEnded)setError(e.message)}finally{setBusy(false)}}
 async function auth(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));await action(async()=>{const b=await api(setup?'setup':signup?'signup':'login',d);expectedUserId=b.user.id;setUser(b.user);setSetup(false);setSignup(false);setView('mine');setAlbum('all');setFamilyMember('all')})}
 function navigate(v:string){setView(v);setAlbum('all');setFamilyMember('all');setError('')}
 function refreshQueue(){setJobs([...queue.current])}
 async function thumbnail(file:File,mid:string){if(!file.type.startsWith('image/'))return;try{const bitmap=await createImageBitmap(file);const canvas=document.createElement('canvas');const scale=Math.min(1,600/Math.max(bitmap.width,bitmap.height));canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d')!.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const blob=await new Promise<Blob|null>(r=>canvas.toBlob(r,'image/jpeg',.75));if(blob)await fetch(API+'media/'+mid+'/thumbnail',{method:'PUT',body:blob})}catch{}}
 async function uploadFiles(files:File[]){if(running)return;const generation=sessionGeneration.current;const assertSession=()=>{if(generation!==sessionGeneration.current)throw new Error('Sign in again before uploading.');};if(files.length){queue.current.push(...files.map(file=>({file,part:1,verify:1,completed:false,status:'Waiting',progress:0})));refreshQueue()}setRunning(true);setError('');
 try{for(const job of queue.current){if(generation!==sessionGeneration.current)break;if(job.done)continue;job.error=undefined;try{if(!job.id){const b=await api('uploads',{name:job.file.name,size:job.file.size,type:job.file.type,album:album==='all'?null:album,taken:job.file.lastModified});job.id=b.id}const chunk=8*1024*1024,total=Math.ceil(job.file.size/chunk);
 if(!job.completed){for(let n=job.part;n<=total;n++){assertSession();job.status='Uploading';job.progress=Math.round((n-1)/total*80);refreshQueue();const data=await job.file.slice((n-1)*chunk,n*chunk).arrayBuffer();const checksum=await hash(data);const res=await fetch(API+'uploads/'+job.id+'/part?part='+n,{method:'PUT',headers:{'x-content-sha256':checksum},body:data});if(!res.ok)throw new Error(((await res.json()) as any).error);job.part=n+1}assertSession();await api('uploads/'+job.id+'/complete',{});job.completed=true}
 for(let n=job.verify;n<=total;n++){assertSession();job.status='Checking stored original';job.progress=80+Math.round((n-1)/total*20);refreshQueue();await api('uploads/'+job.id+'/verify',{part:n});job.verify=n+1}
 job.status='Verified';job.progress=100;job.done=true;refreshQueue();await thumbnail(job.file,job.id!);
 }catch(e:any){job.status='Needs retry';job.error=e.message;refreshQueue()}}}finally{setRunning(false);refreshQueue();if(generation===sessionGeneration.current)await load()}}
 async function openShare(m:any){setSelected(m);await action(async()=>{const b=await api('media/'+m.id+'/shares');setRecipients(b.recipients);setModal('share')})}
 const canEdit=(m:any)=>m.owner===user?.id||user?.role==='owner';
 const heading=view==='mine'?'Your collection':view==='shared'?'Shared with you':view==='family'?'Family collection':view==='trash'?'Recently removed':view==='account'?'Account Center':'Family accounts';
 const brand=<div className="brand"><span className="brand-icon"><Camera size={23}/></span><span>The Family Photo Album<span className="brand-sub">A place for your memories</span></span></div>;
 if(loading)return <main className="auth-page">{brand}<p role="status">Opening your vault…</p></main>;
 if(recovery)return <main className="auth-page"><PasswordRecovery api={api}/></main>;
 if(!user)return <main className="auth-page"><div className="auth-wrap"><div className="auth-intro">{brand}<div className="intro-mark"><LockKeyhole size={44}/></div><h1>A little more space.<br/>Every memory kept.</h1><p>Your photos and videos, together in one private place. Share a moment with just the people you choose.</p><div className="intro-foot"><ShieldCheck size={18}/> Original files. Personal collections.</div></div><section className="auth-card"><span className="eyebrow">YOUR FAMILY’S PRIVATE SPACE</span><h2>{setup?'Set up your family photo album':signup?'Create your account':'Welcome back'}</h2><p>{setup?'Create the primary admin account to get started.':signup?'Create a private collection for your photos and videos.':'Sign in to your family account.'}</p><form onSubmit={auth}>{setup&&<><label>Setup key<Input name="key" type="password" required autoComplete="off"/></label><label>Your name<Input name="name" required autoComplete="name"/></label></>}{signup&&<label>Your name<Input name="name" required maxLength={80} autoComplete="name"/></label>}<label>Username<Input name="username" required autoComplete="username" autoCapitalize="none" pattern="[a-zA-Z0-9_.-]{3,40}"/></label><label>Password<Input name="password" type="password" required minLength={setup||signup?8:undefined} maxLength={128} autoComplete={setup||signup?'new-password':'current-password'}/></label>{signup&&<label>Confirm password<Input name="confirm" type="password" required minLength={8} maxLength={128} autoComplete="new-password"/></label>}<Button disabled={busy} type="submit">{busy?'Please wait…':setup?'Create primary admin account':signup?'Create account':'Sign in'}<ChevronRight size={16}/></Button></form>{!setup&&signupEnabled&&!signup&&<Button variant="outline" asChild><a href="/?signup=1">Create an account</a></Button>}{signup&&<Button variant="link" asChild><a href="/">Already have an account? Sign in</a></Button>}{!setup&&!signup&&<Button variant="link" asChild><a href="/?reset-password=1">Forgot password?</a></Button>}{error&&<p role="alert" className="error">{error}</p>}<div className="auth-note"><LockKeyhole size={16}/><span>{setup?'The setup key is provided privately to the primary admin.':'Need an account or help signing in? Ask your family admin.'}</span></div></section></div></main>;
 return <div className="app-shell"><header className="topbar">{brand}<div className="top-actions"><span className="privacy"><LockKeyhole size={15}/> Private by default</span><button className="account-chip" onClick={()=>navigate('account')} title="Account Center" aria-label="Open Account Center"><span className="avatar">{user.name.slice(0,1).toUpperCase()}</span><span>{user.name}<small>{roleName(user.role)}</small></span></button><Button variant="ghost" size="icon" aria-label="Sign out" disabled={running} onClick={()=>action(async()=>{await api('logout',{});setUser(null);setMedia([]);queue.current=[];setJobs([])})}><LogOut/></Button></div></header>
 <SidebarProvider className="workspace"><Sidebar collapsible="none" className="rail"><span className="eyebrow">YOUR VAULT</span><nav aria-label="Collection navigation">{[['mine','My collection',Images],['shared','Shared with me',Share2],['trash','Recently removed',Trash2],['account','Account Center',KeyRound],...(user.role==='owner'?[['family','All family media',ShieldCheck]]:[])].map(([v,label,Icon]:any)=><button key={v} className={view===v?'active':''} onClick={()=>navigate(v)}><Icon size={19}/>{label}{v==='mine'&&<span className="nav-count">{stats.count}</span>}</button>)}</nav><div className="album-heading"><span className="eyebrow">ALBUMS</span><button aria-label="Create album" onClick={()=>setModal('album')}><Plus size={17}/></button></div><div className="album-nav">{albums.map(a=><button key={a.id} className={album===a.id?'active':''} onClick={()=>{setView('mine');setAlbum(a.id)}}><Folder size={17}/><span>{a.name}</span></button>)}{!albums.length&&<p>Make a home for holidays,<br/>milestones, and everyday life.</p>}</div>{['owner','admin'].includes(user.role)&&<button className={'manage-link '+(view==='accounts'?'active':'')} onClick={()=>navigate('accounts')}><Users size={19}/>Family accounts</button>}<div className="storage-note"><Cloud size={21}/><strong>{bytes(stats.bytes)} stored</strong><p>{stats.count} original {stats.count===1?'file':'files'} in your collection</p></div></Sidebar>
 <main className="main"><div className="mobile-nav"><Select value={view} onValueChange={navigate}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="mine">My collection</SelectItem><SelectItem value="shared">Shared with me</SelectItem><SelectItem value="trash">Recently removed</SelectItem><SelectItem value="account">Account Center</SelectItem>{user.role==='owner'&&<SelectItem value="family">All family media</SelectItem>}{['owner','admin'].includes(user.role)&&<SelectItem value="accounts">Family accounts</SelectItem>}</SelectContent></Select></div><div className="page-heading"><div><div className="breadcrumb">The Family Photo Album <ChevronRight size={13}/>{view==='accounts'?'Manage':'Library'}</div><h1>{album!=='all'?(albums.find(a=>a.id===album)?.name||'Album'):heading}</h1><p>{view==='account'?'Your profile, password, and recovery settings.':view==='accounts'?'Create accounts and help your family sign in.':view==='shared'?'Moments your family chose to share with you.':view==='family'?'Primary admin access to every family member’s stored media.':view==='trash'?'Removed from your collection. Restore these files at any time.':'Room on your phone. Memories right here.'}</p></div>{view!=='account'&&<Button onClick={()=>setModal(view==='accounts'?'member':'upload')} disabled={user.mustChange}><Plus size={18}/>{view==='accounts'?'Add family member':'Upload memories'}</Button>}</div>
 {error&&<div role="alert" className="error">{error}<button onClick={()=>setError('')} aria-label="Dismiss error">×</button></div>}{notice&&<div role="status" className="success">{notice}<button onClick={()=>setNotice('')} aria-label="Dismiss message">×</button></div>}
 {user.mustChange?<section className="empty"><KeyRound/><h2>Choose your own password</h2><p>Replace the temporary password from your admin before opening your collection.</p><Button onClick={()=>setModal('password')}>Change password</Button></section>:view==='account'?<AccountCenter key={user.id} user={user} api={api} onUser={setUser} onPassword={()=>setModal('password')}/>:view==='accounts'?<>{user.role==='owner'&&<PublicSignupSettings api={api}/>}<div className="permission-note"><ShieldCheck size={20}/><p><strong>Everyone has their own space.</strong> Admins manage member accounts. Sharing grants viewing and downloading access.</p></div><div className="members-list">{members.map(m=><div className="member-row" key={m.id}><span className="avatar">{m.name[0]}</span><div className="member-name"><strong>{m.name}</strong><span>@{m.username}</span></div><span className="role-badge">{m.deleting?'Deleting':m.active?roleName(m.role):'Disabled'}</span>{m.role!=='owner'&&m.id!==user.id&&<div className="member-actions">{user.role==='owner'?<Button variant="outline" onClick={()=>{setTarget(m);setModal('manage')}}>{m.deleting?'Resume deletion':'Manage account'}</Button>:!m.deleting&&<><Button variant="outline" onClick={()=>{setTarget(m);setModal('role')}}>Change access</Button>{m.role==='member'&&<><Button variant="outline" onClick={()=>{setTarget(m);setModal('reset')}}>Reset password</Button><Button variant="ghost" onClick={()=>setConfirm({kind:'access',member:m})}>{m.active?'Disable':'Enable'}</Button></>}</>}</div>}</div>)}</div></>:<><div className="collection-tools"><Tabs value={view==='shared'?'shared':'mine'} onValueChange={navigate}><TabsList variant="line"><TabsTrigger value="mine"><Images/>My collection</TabsTrigger><TabsTrigger value="shared"><Share2/>Shared with me</TabsTrigger></TabsList></Tabs><div className="album-filter">{user.role==='owner'&&view==='family'?<Select value={familyMember} onValueChange={setFamilyMember}><SelectTrigger aria-label="Filter by family member"><SelectValue placeholder="All family members"/></SelectTrigger><SelectContent><SelectItem value="all">All family members</SelectItem>{members.map(m=><SelectItem key={m.id} value={m.id}>{m.name}{!m.active?' (disabled)':''}</SelectItem>)}</SelectContent></Select>:<><Select value={album} onValueChange={a=>{setView('mine');setAlbum(a)}}><SelectTrigger><SelectValue placeholder="All albums"/></SelectTrigger><SelectContent><SelectItem value="all">All albums</SelectItem>{albums.map(a=><SelectItem key={a.id} value={a.id}>{a.name}</SelectItem>)}</SelectContent></Select><Button variant="outline" size="icon" aria-label="Create album" onClick={()=>setModal('album')}><Plus/></Button></>}</div></div>
 {fetching&&!media.length?<div className="empty" role="status"><Cloud/><h2>Loading your collection…</h2></div>:!media.length?<section className="empty"><span className="empty-icon">{view==='shared'?<Share2 size={34}/>:view==='trash'?<Trash2 size={34}/>:<Images size={34}/>}</span><h2>{view==='shared'?'A shared moment starts with family':view==='trash'?'Nothing removed':album!=='all'?'Make this album yours':'Your memories belong here'}</h2><p>{view==='shared'?'Photos and videos appear here when a family member shares them with you.':view==='trash'?'Files you remove will be kept here until you restore them. They continue to use storage.':'Upload photos and videos in their original quality. Organize them into albums and choose which family members to share them with.'}</p>{!['shared','trash'].includes(view)&&<Button onClick={()=>setModal('upload')}><Upload size={18}/>Upload your first memories</Button>}</section>:<><div className="result-label"><span>{media.length} {media.length===1?'memory':'memories'}{more?' shown':''}</span><span>Newest uploads first</span></div><div className="media-grid">{media.map(m=><article className="media-card" key={m.id}><button className="media-preview" onClick={()=>{setSelected(m);setModal('detail')}} aria-label={'Open '+m.name}>{m.thumbnail&&!m.deleted?<img loading="lazy" src={API+'media/'+m.id+'/thumbnail'} alt={m.name}/>:<div className="file-preview">{m.type.startsWith('video/')?<Film size={38}/>:<ImageIcon size={38}/>}<span>{m.type.split('/')[1].toUpperCase()} original</span></div>}{m.type.startsWith('video/')&&<span className="video-badge"><Film size={13}/>Video</span>}<span className="verified-badge"><ShieldCheck size={13}/>Verified</span></button><div className="media-info"><strong title={m.name}>{m.name}</strong><p>{view==='shared'||view==='family'?m.owner_name:(m.album_name||'No album')}<span>·</span>{bytes(m.size)}</p><div className="card-bottom"><span>{m.shared_count?<><Users size={13}/>{m.shared_count} shared</>:<><LockKeyhole size={13}/>Private</>}</span>{canEdit(m)&&!m.deleted&&<button aria-label={'Share '+m.name} onClick={()=>openShare(m)}><Share2 size={16}/></button>}{m.deleted&&<button onClick={()=>action(async()=>{await api('media/'+m.id+'/restore',{});await load()})}>Restore</button>}</div></div></article>)}</div>{more&&<Button className="load-more" variant="outline" disabled={fetching} onClick={()=>load(true)}>Load more memories</Button>}</>}
 </>}
 </main></SidebarProvider>
 <Dialog open={!!modal} onOpenChange={o=>{if(!o)setModal('')}}><DialogContent className={modal==='detail'?'vault-dialog detail-dialog':'vault-dialog'}><DialogTitle>{({upload:'Upload memories',album:'Create an album',share:'Share this memory',member:'Add a family member',reset:'Reset password',role:'Change account access',manage:'Manage account',password:'Change your password',detail:selected?.name} as any)[modal]||'The Family Photo Album'}</DialogTitle><DialogDescription>{modal==='upload'?'Original photos and videos, up to 20 GB each. Keep this page open while uploading and checking.':modal==='share'?'Select exactly who can view and download this file. You can remove access later.':modal==='member'?'Give the password to your family member privately. Choose whether they must change it at first sign-in.':modal==='manage'?'Edit this account’s profile, credentials, and access. Saving changes signs the member out.':modal==='role'?'Choose Member or Admin. The account will be signed out so the new access level takes effect. Admin access does not grant access to private family media.':modal==='reset'?'This signs the member out on all devices and clears their recovery questions. Choose whether they must change the new password at next sign-in.':modal==='detail'?'Your original file is stored without compression.':'Your family’s private space.'}</DialogDescription>
 {modal==='upload'&&<><input ref={fileInput} type="file" multiple accept="image/*,video/*,.heic,.heif,.mov,.m4v" hidden onChange={e=>{const f=Array.from(e.target.files||[]);e.target.value='';uploadFiles(f)}}/><button className="upload-drop" disabled={running} onClick={()=>fileInput.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(!running)uploadFiles(Array.from(e.dataTransfer.files))}}><span><Upload size={27}/></span><strong>Choose photos & videos</strong><p>or drop files here</p><small>{album==='all'?'Added to your collection':'Added to '+albums.find(a=>a.id===album)?.name}</small></button><div className="upload-list">{jobs.map((j,i)=><div className="upload-job" key={i}><div><strong>{j.file.name}</strong><span>{j.done?<Check size={15}/>:j.progress+'%'}</span></div><progress value={j.progress} max={100}/><small className={j.error?'error-text':''}>{j.error||j.status}</small></div>)}</div>{jobs.some(j=>j.error)&&<Button disabled={running} onClick={()=>uploadFiles([])}>Retry unfinished uploads</Button>}<div className="permission-note"><ShieldCheck size={22}/><p>Wait for <strong>Verified</strong>, then open and download an original to check it before removing your phone copy. Keep another backup of irreplaceable memories.</p></div><p className="fine-print">This website uploads files you select. It cannot automatically back up your phone in the background or delete phone photos.</p></>}
 {modal==='manage'&&target&&<MemberEditor key={target.id} memberId={target.id} api={api} onSaved={async message=>{setModal('');setNotice(message);await load()}}/>}
 {modal==='role'&&target&&<form onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);action(async()=>{await api('members/'+target.id+'/role',{role:d.get('role')});setModal('');setNotice('Access level updated. The member must sign in again.');await load()})}}><p>Update access for {target.name} (@{target.username}).</p><label>Access level<Select name="role" defaultValue={target.role}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="member">Member</SelectItem><SelectItem value="admin">Admin</SelectItem></SelectContent></Select></label><Button disabled={busy}>Save access level</Button></form>}
 {modal==='album'&&<form onSubmit={e=>{e.preventDefault();const b=Object.fromEntries(new FormData(e.currentTarget));action(async()=>{await api('albums',b);await load();setModal('')})}}><label>Album name<Input name="name" required maxLength={80} placeholder="Summer in Alaska"/></label><Button disabled={busy}>Create album</Button></form>}
 {modal==='share'&&<><div className="share-members">{members.filter(m=>m.active&&m.id!==selected.owner&&m.role!=='owner').map(m=><label className="share-member" key={m.id}><Checkbox checked={recipients.includes(m.id)} onCheckedChange={checked=>setRecipients(old=>checked?[...old,m.id]:old.filter(x=>x!==m.id))}/><span className="avatar">{m.name[0]}</span><span>{m.name}<small>@{m.username}</small></span></label>)}{members.filter(m=>m.active&&m.id!==selected.owner&&m.role!=='owner').length===0&&<p>No other family members yet. An admin can add them in Family accounts.</p>}</div><p className="fine-print">Removing a share cannot remove copies someone already downloaded.</p><Button disabled={busy} onClick={()=>action(async()=>{await api('media/'+selected.id+'/shares',{recipients});setModal('');setNotice('Sharing updated.');await load()})}>Save sharing</Button></>}
 {['member','reset','password'].includes(modal)&&<form onSubmit={e=>{e.preventDefault();const b=Object.fromEntries(new FormData(e.currentTarget));action(async()=>{if(modal==='member')await api('members',{...b,mustChange:b.mustChange==='on'});if(modal==='reset')await api('members/'+target.id+'/reset',{...b,mustChange:b.mustChange==='on'});if(modal==='password'){if(b.password!==b.confirm)throw new Error('The new passwords do not match.');const m=await api('password',b);setUser(m.user)}setModal('');setNotice(modal==='reset'?(b.mustChange==='on'?'Password reset. The member must choose a new password at next sign-in.':'Password reset. The member can sign in with the new password without being required to change it.'):'Account updated.');if(modal!=='password')await load()})}}>{modal==='member'&&<><label>Full name<Input name="name" required maxLength={80}/></label><label>Username<Input name="username" required pattern="[a-zA-Z0-9_.-]{3,40}" autoCapitalize="none" autoComplete="off"/></label>{['owner','admin'].includes(user.role)&&<label>Account role<Select name="role" defaultValue="member"><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="member">Family member</SelectItem><SelectItem value="admin">Admin</SelectItem></SelectContent></Select></label>}</>}{modal==='password'&&<label>Current password<Input name="current" type="password" required maxLength={128} autoComplete="current-password"/></label>}<label>{modal==='member'?'Initial password':'New password'}<Input name="password" type="password" required minLength={8} maxLength={128} autoComplete="new-password"/><small>At least 8 characters.</small></label>{modal==='password'&&<label>Confirm new password<Input name="confirm" type="password" required minLength={8} autoComplete="new-password"/></label>}{modal!=='password'&&<label className="reset-choice"><input name="mustChange" type="checkbox" defaultChecked/><span>Require password change at next sign-in</span></label>}<Button disabled={busy}>{busy?'Saving…':modal==='member'?'Create account':'Save password'}</Button></form>}
 {modal==='detail'&&selected&&<><div className="detail-media">{selected.deleted?<p>Restore this file to open it.</p>:selected.type.startsWith('video/')?<video controls preload="metadata" playsInline src={API+'media/'+selected.id+'/file'}/>:<img src={API+'media/'+selected.id+'/file'} alt={selected.name} onError={e=>{e.currentTarget.style.display='none'}}/>}</div><p className="fine-print">If this format does not preview on your device, download the original to open it in a compatible app. Live Photos require both the photo and video files to preserve both parts.</p><div className="detail-meta"><span>{bytes(selected.size)}</span><span>Uploaded {new Date(selected.created).toLocaleDateString()}</span><span>By {selected.owner_name}</span></div>{!selected.deleted&&<div className="detail-actions"><Button asChild><a href={API+'media/'+selected.id+'/file?download=1'} download><ArrowDownToLine/>Download original</a></Button>{canEdit(selected)&&<Button variant="outline" onClick={()=>openShare(selected)}><Share2/>Share</Button>}</div>}{canEdit(selected)&&<><label>Album<Select value={selected.album||'none'} onValueChange={a=>action(async()=>{await api('media/'+selected.id+'/album',{album:a==='none'?null:a});setSelected({...selected,album:a==='none'?null:a});await load()})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">No album</SelectItem>{albums.filter(a=>a.owner===selected.owner).map(a=><SelectItem key={a.id} value={a.id}>{a.name}</SelectItem>)}</SelectContent></Select></label>{selected.deleted?<Button variant="outline" onClick={()=>action(async()=>{await api('media/'+selected.id+'/restore',{});setModal('');await load()})}><RotateCcw/>Restore file</Button>:<Button variant="ghost" className="remove-button" onClick={()=>setConfirm({kind:'trash',media:selected})}><Trash2/>Move to recently removed</Button>}</>}</>}
 {error&&<p className="error" role="alert">{error}</p>}
 </DialogContent></Dialog>
 <AlertDialog open={!!confirm} onOpenChange={o=>{if(!o)setConfirm(null)}}><AlertDialogContent><AlertDialogTitle>{confirm?.kind==='trash'?'Remove this memory from your collection?':(confirm?.member?.active?'Disable':'Enable')+' this account?'}</AlertDialogTitle><AlertDialogDescription>{confirm?.kind==='trash'?'It will move to Recently removed and remain recoverable. Family members will no longer be able to open it.':confirm?.member?.active?'This will sign the member out and block access. Their media will stay stored.':'The member will be able to sign in again.'}</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction onClick={()=>action(async()=>{if(confirm.kind==='trash'){await api('media/'+confirm.media.id+'/trash',{});setModal('')}else await api('members/'+confirm.member.id+'/access',{active:!confirm.member.active});setConfirm(null);await load()})}>Continue</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </div>
}
